### ISSUE TITLE
Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "engine" is null

### ISSUE THREAD

**Issue by matthw** [OALabs/hashdb-ghidra#12]
The plugin doesn't run anymore with newer JDK version.

I'm running Ghidra 10.2.2 with OpenJDK 17 and whenever i'm trying to look up a hash i'm getting the following stack trace:

```
[HashDB] Exception during resolution: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "engine" is null
	at HashDB.applyTransformation(HashDB.java:1531)
	at HashDB.transformHash(HashDB.java:1521)
	at HashDB.transformHashes(HashDB.java:1337)
	at HashDB.resolveHashes(HashDB.java:1484)
	at HashDB$HashTable$1Resolver.doInBackground(HashDB.java:547)
	at HashDB$HashTable$1Resolver.doInBackground(HashDB.java:534)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

this might be due to the Nashorn JavaScript engine being deprecated: https://openjdk.org/jeps/335

**Comment by matthw** [comment]
Duplicate #7 - sorry

**Comment by matthw** [comment]
duplicate #7
